### ISSUE TITLE
nwb_gallery_prototype error

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-docutils#14]
I ran:
```
nwb_gallery_prototype docs/gallery/general/extensions.py
```

error:

```python
Traceback (most recent call last):
  File "/Users/bendichter/anaconda3/bin/nwb_gallery_prototype", line 11, in <module>
    sys.exit(main())
  File "/Users/bendichter/anaconda3/lib/python3.6/site-packages/nwb_docutils/sg_prototype.py", line 124, in main
    return build(src_file, tgt_dir=tgt_dir, open_html=open_html)
  File "/Users/bendichter/anaconda3/lib/python3.6/site-packages/nwb_docutils/sg_prototype.py", line 54, in build
    shutil.copy(src_file, os.path.join(temp_dir, 'docs', 'gallery', os.path.basename(src_file)))
  File "/Users/bendichter/anaconda3/lib/python3.6/shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/bendichter/anaconda3/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'd'
```

**Comment by bendichter** [comment]
This looks similar to #10

**Comment by bendichter** [comment]
I'm in python3 if that matters

**Comment by nicain** [comment]
This is fixed in the repo, but that state is not pushed to the package index. Clone and pip install from the local clone and you should be all set

**Comment by bendichter** [comment]
oh ok thanks

**Comment by bendichter** [comment]
I removed the repo, cloned it again, and pip installed it with `pip install -e .`. Now `pip list` shows
`nwb-docutils (0.2.1.post0.dev4, /Users/bendichter/dev/nwb-docutils)` but I get the same error

**Comment by bendichter** [comment]
now it's working. Weird.
