### ISSUE TITLE
Generating extension docs yields encoding error

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-docutils#29]
If I pip install nwb-docutils and then run `nwb_init_sphinx_extension_doc` on Windows 10, Python 3.7, I get the following error:
```
Creating file C:\Users\Ryan\Documents\NWB\nwbext_simulation_output\docs\source\conf.py.
Creating file C:\Users\Ryan\Documents\NWB\nwbext_simulation_output\docs\source\index.rst.
Creating file C:\Users\Ryan\Documents\NWB\nwbext_simulation_output\docs\make.bat.

Finished: An initial directory structure has been created.

You should now populate your master file C:\Users\Ryan\Documents\NWB\nwbext_simulation_output\docs\source\index.rst and create other documentation
source files. Use the Makefile to build the docs, like so:
   make builder
where "builder" is one of the supported builders, e.g. html, latex or linkcheck.

Traceback (most recent call last):
  File "c:\users\ryan\anaconda3\envs\nwb-ext-test\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\ryan\anaconda3\envs\nwb-ext-test\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ryan\Anaconda3\envs\nwb-ext-test\Scripts\nwb_init_sphinx_extension_doc.exe\__main__.py", line 9, in <module>
  File "c:\users\ryan\anaconda3\envs\nwb-ext-test\lib\site-packages\nwb_docutils\init_sphinx_extension_doc.py", line 918, in main
    write_custom_conf(**clargs)
  File "c:\users\ryan\anaconda3\envs\nwb-ext-test\lib\site-packages\nwb_docutils\init_sphinx_extension_doc.py", line 784, in write_custom_conf
    outfile.write(custom_doc_autogen_settings)
  File "c:\users\ryan\anaconda3\envs\nwb-ext-test\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2192' in position 3077: character maps to <undefined>
```
\u2192 is the rightwards arrow →
which is in one of the comments generated by `conf_doc_autogen.py`. 

Solution: Encode strings in Unicode before writing, e.g.
`outfile.write(custom_doc_autogen_settings)` -> `outfile.write(custom_doc_autogen_settings.encode('utf8'))`

**Comment by oruebel** [comment]
I think the '-> ' is just in a comment so I think you can just remove it from the file.
